import 'package:gymgenius/domain/entities/food_item.dart';
import 'package:gymgenius/domain/enums/food_category.dart';

const List<FoodItem> cameroonCarbohydrates = [
  FoodItem(
    id: 'cm_rice',
    name: 'White rice (cooked)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 130,
    proteinGPer100g: 2.7,
    carbsGPer100g: 28,
    fatGPer100g: 0.3,
    fiberGPer100g: 0.4,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 158,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_plantain_boiled',
    name: 'Boiled plantain',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 122,
    proteinGPer100g: 1.3,
    carbsGPer100g: 31,
    fatGPer100g: 0.4,
    fiberGPer100g: 2.3,
    defaultPortionLabel: '1 medium',
    defaultPortionGrams: 180,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_plantain_fried',
    name: 'Fried plantain (ripe)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 210,
    proteinGPer100g: 1.5,
    carbsGPer100g: 35,
    fatGPer100g: 8,
    fiberGPer100g: 2.0,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 150,
    tags: ['staple', 'street_food'],
  ),
  FoodItem(
    id: 'cm_cassava',
    name: 'Boiled cassava',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 160,
    proteinGPer100g: 1.4,
    carbsGPer100g: 38,
    fatGPer100g: 0.3,
    fiberGPer100g: 1.8,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 200,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_cassava_bobolo',
    name: 'Bobolo / Miondo (cassava stick)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 150,
    proteinGPer100g: 1.5,
    carbsGPer100g: 35,
    fatGPer100g: 0.5,
    fiberGPer100g: 2.0,
    defaultPortionLabel: '1 piece',
    defaultPortionGrams: 150,
    tags: ['staple', 'traditional'],
  ),
  FoodItem(
    id: 'cm_fufu',
    name: 'Water fufu',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 170,
    proteinGPer100g: 1.2,
    carbsGPer100g: 40,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 ball',
    defaultPortionGrams: 200,
    tags: ['staple', 'traditional'],
  ),
  FoodItem(
    id: 'cm_sweet_potato',
    name: 'Sweet potato (boiled)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 90,
    proteinGPer100g: 2.0,
    carbsGPer100g: 21,
    fatGPer100g: 0.2,
    fiberGPer100g: 3.0,
    defaultPortionLabel: '1 medium',
    defaultPortionGrams: 150,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_yam',
    name: 'Boiled yam',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 118,
    proteinGPer100g: 1.5,
    carbsGPer100g: 28,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 180,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_maize_boiled',
    name: 'Corn / maize (boiled)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 96,
    proteinGPer100g: 3.4,
    carbsGPer100g: 21,
    fatGPer100g: 1.5,
    fiberGPer100g: 2.0,
    defaultPortionLabel: '1 cob',
    defaultPortionGrams: 150,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_cocoyam',
    name: 'Cocoyam (boiled)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 112,
    proteinGPer100g: 1.5,
    carbsGPer100g: 26,
    fatGPer100g: 0.2,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 180,
    tags: ['traditional'],
  ),
  FoodItem(
    id: 'cm_irish_potato',
    name: 'Irish potato (boiled)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 87,
    proteinGPer100g: 1.9,
    carbsGPer100g: 20,
    fatGPer100g: 0.1,
    defaultPortionLabel: '2 medium',
    defaultPortionGrams: 200,
  ),
  FoodItem(
    id: 'cm_bread',
    name: 'Local bread',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 265,
    proteinGPer100g: 9,
    carbsGPer100g: 49,
    fatGPer100g: 3.2,
    defaultPortionLabel: '2 slices',
    defaultPortionGrams: 70,
    tags: ['breakfast'],
  ),
  FoodItem(
    id: 'cm_beignets',
    name: 'Beignets (doughnuts)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 380,
    proteinGPer100g: 6,
    carbsGPer100g: 45,
    fatGPer100g: 20,
    defaultPortionLabel: '1 large piece',
    defaultPortionGrams: 60,
    tags: ['breakfast', 'street_food'],
  ),
  FoodItem(
    id: 'cm_corn_flour',
    name: 'Corn flour (maize meal)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 365,
    proteinGPer100g: 7,
    carbsGPer100g: 76,
    fatGPer100g: 1.5,
    defaultPortionLabel: '1 cup (80g)',
    defaultPortionGrams: 80,
    tags: ['staple', 'flour'],
  ),
  FoodItem(
    id: 'cm_macaroni',
    name: 'Macaroni / pasta (cooked)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 131,
    proteinGPer100g: 5.0,
    carbsGPer100g: 25,
    fatGPer100g: 1.1,
    fiberGPer100g: 1.8,
    defaultPortionLabel: '1 cup cooked',
    defaultPortionGrams: 140,
    tags: ['staple'],
  ),
  FoodItem(
    id: 'cm_corn_couscous',
    name: 'Corn couscous (couscous de maïs)',
    country: 'Cameroon',
    category: FoodCategory.carbohydrate,
    caloriesPer100g: 120,
    proteinGPer100g: 2.5,
    carbsGPer100g: 26,
    fatGPer100g: 1.0,
    fiberGPer100g: 2.0,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 180,
    tags: ['staple', 'traditional'],
  ),
];
