import 'package:gymgenius/domain/entities/food_item.dart';
import 'package:gymgenius/domain/enums/food_category.dart';

const List<FoodItem> cameroonFats = [
  FoodItem(
    id: 'cm_avocado',
    name: 'Avocado',
    country: 'Cameroon',
    category: FoodCategory.fat,
    caloriesPer100g: 160,
    proteinGPer100g: 2,
    carbsGPer100g: 8.5,
    fatGPer100g: 15,
    fiberGPer100g: 6.7,
    defaultPortionLabel: '1/2 fruit',
    defaultPortionGrams: 70,
    tags: ['plant'],
  ),
  FoodItem(
    id: 'cm_palm_oil',
    name: 'Palm oil',
    country: 'Cameroon',
    category: FoodCategory.fat,
    caloriesPer100g: 884,
    proteinGPer100g: 0,
    carbsGPer100g: 0,
    fatGPer100g: 100,
    defaultPortionLabel: '1 tbsp',
    defaultPortionGrams: 14,
    tags: ['cooking'],
  ),
  FoodItem(
    id: 'cm_peanut_paste',
    name: 'Peanut paste',
    country: 'Cameroon',
    category: FoodCategory.fat,
    caloriesPer100g: 588,
    proteinGPer100g: 25,
    carbsGPer100g: 20,
    fatGPer100g: 50,
    defaultPortionLabel: '1 tbsp',
    defaultPortionGrams: 16,
    allergens: ['peanut'],
  ),
  FoodItem(
    id: 'cm_peanut_oil',
    name: 'Peanut oil',
    country: 'Cameroon',
    category: FoodCategory.fat,
    caloriesPer100g: 884,
    proteinGPer100g: 0,
    carbsGPer100g: 0,
    fatGPer100g: 100,
    defaultPortionLabel: '1 tbsp (10g)',
    defaultPortionGrams: 10,
    tags: ['cooking'],
  ),
  FoodItem(
    id: 'cm_ogbono',
    name: 'Ogbono (wild mango seeds)',
    country: 'Cameroon',
    category: FoodCategory.fat,
    caloriesPer100g: 500,
    proteinGPer100g: 10,
    carbsGPer100g: 20,
    fatGPer100g: 45,
    defaultPortionLabel: '1 tbsp (15g)',
    defaultPortionGrams: 15,
    tags: ['traditional', 'soup'],
  ),

  // -------------------------------------------------------------------------
  // Additional Cameroon seed / nut ingredients
  // -------------------------------------------------------------------------

  FoodItem(
    id: 'cm_egusi',
    name: 'Egusi / melon seeds',
    country: 'Cameroon',
    category: FoodCategory.fat,
    caloriesPer100g: 557,
    proteinGPer100g: 28,
    carbsGPer100g: 15,
    fatGPer100g: 47,
    fiberGPer100g: 4.0,
    defaultPortionLabel: '2 tbsp (30g)',
    defaultPortionGrams: 30,
    tags: ['traditional'],
  ),
];
