import 'package:gymgenius/domain/entities/food_item.dart';
import 'package:gymgenius/domain/enums/budget_level.dart';
import 'package:gymgenius/domain/enums/food_category.dart';

const List<FoodItem> cameroonProteins = [
  FoodItem(
    id: 'cm_eggs',
    name: 'Eggs',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 155,
    proteinGPer100g: 13,
    carbsGPer100g: 1.1,
    fatGPer100g: 11,
    defaultPortionLabel: '2 eggs',
    defaultPortionGrams: 100,
    allergens: ['egg'],
    tags: ['animal'],
  ),
  FoodItem(
    id: 'cm_chicken',
    name: 'Grilled chicken',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 165,
    proteinGPer100g: 31,
    carbsGPer100g: 0,
    fatGPer100g: 3.6,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 150,
    minBudget: BudgetLevel.medium,
    tags: ['animal'],
  ),
  FoodItem(
    id: 'cm_chicken_dg',
    name: 'Chicken (DG style)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 200,
    proteinGPer100g: 28,
    carbsGPer100g: 2,
    fatGPer100g: 10,
    defaultPortionLabel: '1 piece',
    defaultPortionGrams: 120,
    minBudget: BudgetLevel.medium,
    tags: ['animal', 'traditional'],
  ),
  FoodItem(
    id: 'cm_beef',
    name: 'Beef',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 250,
    proteinGPer100g: 26,
    carbsGPer100g: 0,
    fatGPer100g: 15,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 120,
    minBudget: BudgetLevel.medium,
    tags: ['animal'],
  ),
  FoodItem(
    id: 'cm_beef_kondre',
    name: 'Kondré (beef tripe / cow skin)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 180,
    proteinGPer100g: 22,
    carbsGPer100g: 0,
    fatGPer100g: 10,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 150,
    minBudget: BudgetLevel.medium,
    tags: ['animal', 'traditional'],
  ),
  FoodItem(
    id: 'cm_fish',
    name: 'Fresh fish (tilapia)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 128,
    proteinGPer100g: 26,
    carbsGPer100g: 0,
    fatGPer100g: 2.7,
    defaultPortionLabel: '1 fillet',
    defaultPortionGrams: 150,
    allergens: ['fish'],
    tags: ['animal'],
  ),
  FoodItem(
    id: 'cm_smoked_fish',
    name: 'Smoked fish',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 180,
    proteinGPer100g: 32,
    carbsGPer100g: 0,
    fatGPer100g: 5,
    defaultPortionLabel: '1 piece',
    defaultPortionGrams: 80,
    allergens: ['fish'],
    tags: ['animal', 'traditional'],
  ),
  FoodItem(
    id: 'cm_sardines',
    name: 'Sardines (canned)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 208,
    proteinGPer100g: 25,
    carbsGPer100g: 0,
    fatGPer100g: 11,
    defaultPortionLabel: '1 tin',
    defaultPortionGrams: 100,
    allergens: ['fish'],
    tags: ['animal'],
  ),
  FoodItem(
    id: 'cm_beans',
    name: 'Beans (cooked)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 127,
    proteinGPer100g: 8.7,
    carbsGPer100g: 22.8,
    fatGPer100g: 0.5,
    fiberGPer100g: 6.4,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 180,
    tags: ['plant', 'staple'],
  ),
  FoodItem(
    id: 'cm_koki_beans',
    name: 'Black-eyed peas (for koki)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 116,
    proteinGPer100g: 7.7,
    carbsGPer100g: 20.8,
    fatGPer100g: 0.5,
    defaultPortionLabel: '1 cup',
    defaultPortionGrams: 170,
    tags: ['plant', 'traditional'],
  ),
  FoodItem(
    id: 'cm_soy_flour',
    name: 'Soy flour (full fat)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 405,
    proteinGPer100g: 36,
    carbsGPer100g: 31,
    fatGPer100g: 19,
    defaultPortionLabel: '1 tbsp (20g)',
    defaultPortionGrams: 20,
    tags: ['plant', 'flour'],
  ),
  FoodItem(
    id: 'cm_groundnuts',
    name: 'Groundnuts / peanuts',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 567,
    proteinGPer100g: 26,
    carbsGPer100g: 16,
    fatGPer100g: 49,
    defaultPortionLabel: '1 handful',
    defaultPortionGrams: 30,
    allergens: ['peanut'],
    tags: ['plant'],
  ),
  FoodItem(
    id: 'cm_fermented_milk',
    name: 'Fermented milk / Pendidam',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 60,
    proteinGPer100g: 3.2,
    carbsGPer100g: 4.5,
    fatGPer100g: 3.0,
    defaultPortionLabel: '1 glass',
    defaultPortionGrams: 200,
    tags: ['dairy', 'breakfast'],
  ),
  FoodItem(
    id: 'cm_nido_powder',
    name: 'Nido milk powder (full cream)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 496,
    proteinGPer100g: 26,
    carbsGPer100g: 38,
    fatGPer100g: 26,
    defaultPortionLabel: '1 tbsp (10g)',
    defaultPortionGrams: 10,
    tags: ['dairy'],
  ),
  FoodItem(
    id: 'cm_morue',
    name: 'Morue (salted dried cod, prepared)',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 135,
    proteinGPer100g: 29,
    carbsGPer100g: 0,
    fatGPer100g: 1.5,
    defaultPortionLabel: '1 piece',
    defaultPortionGrams: 80,
    allergens: ['fish'],
    tags: ['animal', 'traditional'],
  ),

  // -------------------------------------------------------------------------
  // Additional Cameroon proteins
  // -------------------------------------------------------------------------

  FoodItem(
    id: 'cm_crayfish',
    name: 'Dried crayfish',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 325,
    proteinGPer100g: 63,
    carbsGPer100g: 0,
    fatGPer100g: 6,
    defaultPortionLabel: '2 tbsp (20g)',
    defaultPortionGrams: 20,
    allergens: ['shellfish'],
    tags: ['animal', 'traditional'],
  ),
  FoodItem(
    id: 'cm_goat_meat',
    name: 'Goat meat',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 143,
    proteinGPer100g: 27,
    carbsGPer100g: 0,
    fatGPer100g: 3,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 120,
    minBudget: BudgetLevel.medium,
    tags: ['animal', 'traditional'],
  ),
  FoodItem(
    id: 'cm_beef_tripe',
    name: 'Beef tripe',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 94,
    proteinGPer100g: 12.5,
    carbsGPer100g: 0,
    fatGPer100g: 4,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 120,
    minBudget: BudgetLevel.medium,
    tags: ['animal', 'traditional'],
  ),
  FoodItem(
    id: 'cm_beef_skin',
    name: 'Beef skin / Canda',
    country: 'Cameroon',
    category: FoodCategory.protein,
    caloriesPer100g: 170,
    proteinGPer100g: 25,
    carbsGPer100g: 0,
    fatGPer100g: 8,
    defaultPortionLabel: '1 serving',
    defaultPortionGrams: 100,
    minBudget: BudgetLevel.medium,
    tags: ['animal', 'traditional'],
  ),
];
